import { CanvasElement, DiagramTemplate } from '../types';

export const DIAGRAM_TEMPLATES: DiagramTemplate[] = [
  {
    id: 'flowchart',
    title: 'Flowchart Diagram',
    description: 'Decision flow with process nodes, conditionals, and connecting arrows.',
    category: 'Engineering',
    thumbnail: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=300&q=80',
    elements: [
      // Start Node
      {
        id: 'fc-1',
        type: 'rectangle',
        x: 350,
        y: 100,
        width: 160,
        height: 60,
        angle: 0,
        strokeColor: '#8b5cf6',
        fillColor: 'rgba(139, 92, 246, 0.15)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 1,
        text: 'Start Request',
        fontSize: 18,
        fontFamily: 'Caveat',
        textAlign: 'center',
        zIndex: 1,
        seed: 101,
      },
      // Arrow to Process
      {
        id: 'fc-arr-1',
        type: 'arrow',
        x: 430,
        y: 160,
        width: 0,
        height: 80,
        angle: 0,
        strokeColor: '#8b5cf6',
        fillColor: '#8b5cf6',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        points: [{ x: 0, y: 0 }, { x: 0, y: 80 }],
        zIndex: 2,
        seed: 102,
      },
      // Process 1
      {
        id: 'fc-2',
        type: 'rectangle',
        x: 340,
        y: 240,
        width: 180,
        height: 70,
        angle: 0,
        strokeColor: '#3b82f6',
        fillColor: 'rgba(59, 130, 246, 0.15)',
        fillStyle: 'hachure',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: 'Validate JWT Token',
        fontSize: 18,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 3,
        seed: 103,
      },
      // Arrow to Decision
      {
        id: 'fc-arr-2',
        type: 'arrow',
        x: 430,
        y: 310,
        width: 0,
        height: 70,
        angle: 0,
        strokeColor: '#3b82f6',
        fillColor: '#3b82f6',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        points: [{ x: 0, y: 0 }, { x: 0, y: 70 }],
        zIndex: 4,
        seed: 104,
      },
      // Decision Diamond
      {
        id: 'fc-3',
        type: 'diamond',
        x: 340,
        y: 380,
        width: 180,
        height: 100,
        angle: 0,
        strokeColor: '#f59e0b',
        fillColor: 'rgba(245, 158, 11, 0.15)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: 'Is Authorized?',
        fontSize: 18,
        fontFamily: 'Caveat',
        textAlign: 'center',
        zIndex: 5,
        seed: 105,
      },
      // Arrow YES
      {
        id: 'fc-arr-yes',
        type: 'arrow',
        x: 430,
        y: 480,
        width: 0,
        height: 80,
        angle: 0,
        strokeColor: '#10b981',
        fillColor: '#10b981',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        points: [{ x: 0, y: 0 }, { x: 0, y: 80 }],
        zIndex: 6,
        seed: 106,
      },
      // Success Process
      {
        id: 'fc-4',
        type: 'rectangle',
        x: 330,
        y: 560,
        width: 200,
        height: 70,
        angle: 0,
        strokeColor: '#10b981',
        fillColor: 'rgba(16, 185, 129, 0.15)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: 'Serve Whiteboard Data',
        fontSize: 18,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 7,
        seed: 107,
      },
      // Arrow NO to Error
      {
        id: 'fc-arr-no',
        type: 'arrow',
        x: 520,
        y: 430,
        width: 120,
        height: 0,
        angle: 0,
        strokeColor: '#ef4444',
        fillColor: '#ef4444',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        points: [{ x: 0, y: 0 }, { x: 120, y: 0 }],
        zIndex: 8,
        seed: 108,
      },
      // Error Node
      {
        id: 'fc-5',
        type: 'rectangle',
        x: 640,
        y: 395,
        width: 160,
        height: 70,
        angle: 0,
        strokeColor: '#ef4444',
        fillColor: 'rgba(239, 68, 68, 0.15)',
        fillStyle: 'hachure',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: 'Return 403 Forbidden',
        fontSize: 16,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 9,
        seed: 109,
      },
    ],
  },
  {
    id: 'system-architecture',
    title: 'System Architecture',
    description: 'Cloud native multi-tier architecture with gateways, microservices, caches, and databases.',
    category: 'Architecture',
    thumbnail: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=300&q=80',
    elements: [
      // Client
      {
        id: 'sa-client',
        type: 'rectangle',
        x: 100,
        y: 260,
        width: 170,
        height: 90,
        angle: 0,
        strokeColor: '#06b6d4',
        fillColor: 'rgba(6, 182, 212, 0.15)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 1,
        text: '📱 Web / Mobile\nClient App',
        fontSize: 18,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 1,
        seed: 201,
      },
      // Arrow to Gateway
      {
        id: 'sa-arr-1',
        type: 'arrow',
        x: 270,
        y: 305,
        width: 110,
        height: 0,
        angle: 0,
        strokeColor: '#8b5cf6',
        fillColor: '#8b5cf6',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        points: [{ x: 0, y: 0 }, { x: 110, y: 0 }],
        zIndex: 2,
        seed: 202,
      },
      // API Gateway
      {
        id: 'sa-gw',
        type: 'rectangle',
        x: 380,
        y: 200,
        width: 160,
        height: 210,
        angle: 0,
        strokeColor: '#8b5cf6',
        fillColor: 'rgba(139, 92, 246, 0.2)',
        fillStyle: 'cross-hatch',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: '⚡ API Gateway\n& Rate Limiter\n(Socket.IO)',
        fontSize: 18,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 3,
        seed: 203,
      },
      // Microservice 1: Canvas Engine
      {
        id: 'sa-ms1',
        type: 'rectangle',
        x: 610,
        y: 120,
        width: 180,
        height: 80,
        angle: 0,
        strokeColor: '#3b82f6',
        fillColor: 'rgba(59, 130, 246, 0.15)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: '🎨 Canvas Sync\nService',
        fontSize: 16,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 4,
        seed: 204,
      },
      // Microservice 2: Auth Service
      {
        id: 'sa-ms2',
        type: 'rectangle',
        x: 610,
        y: 230,
        width: 180,
        height: 80,
        angle: 0,
        strokeColor: '#ec4899',
        fillColor: 'rgba(236, 72, 153, 0.15)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: '🔐 Auth & User\nService',
        fontSize: 16,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 5,
        seed: 205,
      },
      // Microservice 3: Collaboration & Room
      {
        id: 'sa-ms3',
        type: 'rectangle',
        x: 610,
        y: 340,
        width: 180,
        height: 80,
        angle: 0,
        strokeColor: '#10b981',
        fillColor: 'rgba(16, 185, 129, 0.15)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: '👥 Live Presence\n& Cursors',
        fontSize: 16,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 6,
        seed: 206,
      },
      // Redis Cache
      {
        id: 'sa-redis',
        type: 'ellipse',
        x: 870,
        y: 130,
        width: 150,
        height: 80,
        angle: 0,
        strokeColor: '#ef4444',
        fillColor: 'rgba(239, 68, 68, 0.15)',
        fillStyle: 'hachure',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 0,
        text: '⚡ Redis\nPresence Cache',
        fontSize: 16,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 7,
        seed: 207,
      },
      // PostgreSQL DB
      {
        id: 'sa-db',
        type: 'rectangle',
        x: 870,
        y: 280,
        width: 150,
        height: 120,
        angle: 0,
        strokeColor: '#6366f1',
        fillColor: 'rgba(99, 102, 241, 0.15)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 1,
        text: '🗄️ PostgreSQL\n(Boards & Users)',
        fontSize: 16,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 8,
        seed: 208,
      },
    ],
  },
  {
    id: 'mind-map',
    title: 'Mind Map / Brainstorming',
    description: 'Central concept with interconnected ideas and colorful branches.',
    category: 'Creativity',
    thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=300&q=80',
    elements: [
      // Central Node
      {
        id: 'mm-center',
        type: 'ellipse',
        x: 450,
        y: 260,
        width: 220,
        height: 120,
        angle: 0,
        strokeColor: '#8b5cf6',
        fillColor: 'rgba(139, 92, 246, 0.25)',
        fillStyle: 'solid',
        strokeWidth: 3,
        strokeStyle: 'solid',
        roughness: 1.2,
        opacity: 100,
        roundness: 0,
        text: '🚀 Product Launch\nStrategy 2026',
        fontSize: 22,
        fontFamily: 'Caveat',
        textAlign: 'center',
        zIndex: 1,
        seed: 301,
      },
      // Sticky 1: Top Left
      {
        id: 'mm-st1',
        type: 'sticky',
        x: 180,
        y: 100,
        width: 170,
        height: 140,
        angle: -3,
        strokeColor: '#2563eb',
        fillColor: '#dbeafe',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        strokeStyle: 'solid',
        roughness: 0.8,
        opacity: 100,
        roundness: 0,
        text: 'User Experience:\n• Seamless infinite canvas\n• Real-time hand drawing\n• Dark & light mode themes',
        fontSize: 16,
        fontFamily: 'Caveat',
        textAlign: 'left',
        zIndex: 2,
        seed: 302,
      },
      // Sticky 2: Top Right
      {
        id: 'mm-st2',
        type: 'sticky',
        x: 750,
        y: 100,
        width: 170,
        height: 140,
        angle: 2,
        strokeColor: '#16a34a',
        fillColor: '#dcfce7',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        strokeStyle: 'solid',
        roughness: 0.8,
        opacity: 100,
        roundness: 0,
        text: 'Collaboration:\n• Multi-user live cursors\n• Lock conflict resolution\n• Canvas comments pin',
        fontSize: 16,
        fontFamily: 'Caveat',
        textAlign: 'left',
        zIndex: 3,
        seed: 303,
      },
      // Sticky 3: Bottom Left
      {
        id: 'mm-st3',
        type: 'sticky',
        x: 180,
        y: 380,
        width: 170,
        height: 140,
        angle: 1,
        strokeColor: '#d97706',
        fillColor: '#fef3c7',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        strokeStyle: 'solid',
        roughness: 0.8,
        opacity: 100,
        roundness: 0,
        text: 'Export & Share:\n• High-DPI PNG\n• Scalable SVG\n• Read-only share links',
        fontSize: 16,
        fontFamily: 'Caveat',
        textAlign: 'left',
        zIndex: 4,
        seed: 304,
      },
      // Sticky 4: Bottom Right
      {
        id: 'mm-st4',
        type: 'sticky',
        x: 750,
        y: 380,
        width: 170,
        height: 140,
        angle: -2,
        strokeColor: '#e11d48',
        fillColor: '#ffe4e6',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        strokeStyle: 'solid',
        roughness: 0.8,
        opacity: 100,
        roundness: 0,
        text: 'Architecture:\n• Prisma SQLite / Postgres\n• Socket.IO Realtime Gateway\n• Fast Vite React UI',
        fontSize: 16,
        fontFamily: 'Caveat',
        textAlign: 'left',
        zIndex: 5,
        seed: 305,
      },
    ],
  },
  {
    id: 'sprint-retro',
    title: 'Sprint Retrospective',
    description: 'Agile columns with sticky notes for What Went Well, What to Improve, and Action Items.',
    category: 'Productivity',
    thumbnail: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=300&q=80',
    elements: [
      // Column 1 Header
      {
        id: 'sr-c1',
        type: 'rectangle',
        x: 80,
        y: 80,
        width: 280,
        height: 60,
        angle: 0,
        strokeColor: '#10b981',
        fillColor: 'rgba(16, 185, 129, 0.2)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 1,
        text: '🎉 What Went Well',
        fontSize: 20,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 1,
        seed: 401,
      },
      // Column 2 Header
      {
        id: 'sr-c2',
        type: 'rectangle',
        x: 400,
        y: 80,
        width: 280,
        height: 60,
        angle: 0,
        strokeColor: '#f59e0b',
        fillColor: 'rgba(245, 158, 11, 0.2)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 1,
        text: '🔧 Needs Improvement',
        fontSize: 20,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 2,
        seed: 402,
      },
      // Column 3 Header
      {
        id: 'sr-c3',
        type: 'rectangle',
        x: 720,
        y: 80,
        width: 280,
        height: 60,
        angle: 0,
        strokeColor: '#8b5cf6',
        fillColor: 'rgba(139, 92, 246, 0.2)',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        roundness: 1,
        text: '🎯 Action Items',
        fontSize: 20,
        fontFamily: 'Inter',
        textAlign: 'center',
        zIndex: 3,
        seed: 403,
      },
      // Sticky Notes in Col 1
      {
        id: 'sr-st1',
        type: 'sticky',
        x: 100,
        y: 170,
        width: 240,
        height: 120,
        angle: 1,
        strokeColor: '#16a34a',
        fillColor: '#dcfce7',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        strokeStyle: 'solid',
        roughness: 0.8,
        opacity: 100,
        roundness: 0,
        text: 'Delivered real-time collaboration with zero sync delay!',
        fontSize: 18,
        fontFamily: 'Caveat',
        textAlign: 'left',
        zIndex: 4,
        seed: 404,
      },
      {
        id: 'sr-st2',
        type: 'sticky',
        x: 100,
        y: 310,
        width: 240,
        height: 120,
        angle: -1,
        strokeColor: '#16a34a',
        fillColor: '#dcfce7',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        strokeStyle: 'solid',
        roughness: 0.8,
        opacity: 100,
        roundness: 0,
        text: 'Hand-drawn aesthetics received incredible user feedback!',
        fontSize: 18,
        fontFamily: 'Caveat',
        textAlign: 'left',
        zIndex: 5,
        seed: 405,
      },
      // Sticky Notes in Col 2
      {
        id: 'sr-st3',
        type: 'sticky',
        x: 420,
        y: 170,
        width: 240,
        height: 120,
        angle: -2,
        strokeColor: '#d97706',
        fillColor: '#fef3c7',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        strokeStyle: 'solid',
        roughness: 0.8,
        opacity: 100,
        roundness: 0,
        text: 'Need better touch & pinch zoom support on mobile tablets.',
        fontSize: 18,
        fontFamily: 'Caveat',
        textAlign: 'left',
        zIndex: 6,
        seed: 406,
      },
      // Sticky Notes in Col 3
      {
        id: 'sr-st4',
        type: 'sticky',
        x: 740,
        y: 170,
        width: 240,
        height: 120,
        angle: 1.5,
        strokeColor: '#7c3aed',
        fillColor: '#ede9fe',
        fillStyle: 'solid',
        strokeWidth: 1.5,
        strokeStyle: 'solid',
        roughness: 0.8,
        opacity: 100,
        roundness: 0,
        text: '1. Add SVG vector export\n2. Add version history snapshots\n3. Optimize spatial indexing',
        fontSize: 18,
        fontFamily: 'Caveat',
        textAlign: 'left',
        zIndex: 7,
        seed: 407,
      },
    ],
  },
];
